set_property IOSTANDARD LVCMOS33 [get_ports phy_dir]
set_property IOSTANDARD LVCMOS33 [get_ports phy_clk]
set_property IOSTANDARD LVCMOS33 [get_ports phy_nxt]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst]
set_property IOSTANDARD LVCMOS33 [get_ports phy_stp]
set_property IOSTANDARD LVCMOS33 [get_ports {phy_data[*]}]

set_property PACKAGE_PIN E15 [get_ports phy_dir]
set_property PACKAGE_PIN D15 [get_ports phy_clk]
set_property PACKAGE_PIN J17 [get_ports phy_nxt]
set_property PACKAGE_PIN J18 [get_ports phy_rst]
set_property PACKAGE_PIN K15 [get_ports phy_stp]
set_property PACKAGE_PIN U12 [get_ports {phy_data[7]}]
set_property PACKAGE_PIN V12 [get_ports {phy_data[5]}]
set_property PACKAGE_PIN V10 [get_ports {phy_data[3]}]
set_property PACKAGE_PIN V11 [get_ports {phy_data[1]}]
set_property PACKAGE_PIN U14 [get_ports {phy_data[6]}]
set_property PACKAGE_PIN V14 [get_ports {phy_data[4]}]
set_property PACKAGE_PIN T13 [get_ports {phy_data[2]}]
set_property PACKAGE_PIN U13 [get_ports {phy_data[0]}]

